stages:
  - build
  - test

#build-front:
#  image: node:7.7.4
#  stage: build
#  script: "cd front && npm install && npm install @angular/cli && npm build"

before_script:
  - chmod +x ci/install-chrome
  - chmod +x ci/install-firefox
  - apt-get update -yqqq
  - ci/install-firefox

test-frontend:  
  image: node:7.7.4
  stage: test
  script: 
    - cd front 
    - npm install -g @angular/cli 
    - npm install
    - npm build
    - xvfb-run -a npm test
 
test-server:
  image: maven:3.5.0-jdk-8
  stage: test
  script: "cd server && mvn test"