image: gradle:alpine

stages:
  - build
  - test
  
before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - cd wordstat

build:
  stage: build
  script:
    - gradle build
    
test:
  stage: test
  script:
    - gradle test
